OMM_PACKAGE_DIR = package

OMM_WORK_DIR = omm_workdir
OMM_WORK_DIR_ARCH = $(OMM_WORK_DIR)/$(OMM_USER_PROJECT)/$(OMM_ARCH_CONFIG)/$(OMM_MACH_MCU_CONFIG)
OMM_WORK_SRC_DIR = $(OMM_WORK_DIR_ARCH)/src
OMM_DEPLOY_DIR = $(OMM_WORK_DIR_ARCH)/deploy

OMM_TIMESTAMP_DIR = $(OMM_WORK_DIR)/omm_timestamps

OMM_PKG_WORK_DIR   = $(OMM_WORK_DIR)/$(PROJECT)/$(MACH)/package
OMM_PKG_DEPLOY_DIR = $(OMM_WORK_DIR)/$(PROJECT)/$(MACH)/deploy
OMM_DOWNLOAD_DIR   = $(OMM_WORK_DIR)/download
