OMM_PACKAGE_DIR 	= package
OMM_WORK_DIR 		= omm_workdir
OMM_PKG_WORK_DIR   	= $(OMM_WORK_DIR)/$(PROJECT_NAME)/$(MACH)/package
OMM_PKG_DEPLOY_DIR 	= $(OMM_WORK_DIR)/$(PROJECT_NAME)/$(MACH)/deploy
OMM_DOWNLOAD_DIR   	= $(OMM_WORK_DIR)/download
